AWSTemplateFormatVersion: 2010-09-09
Description: Multi-Region Infrastructure Deployment S3 Example
Resources:
  MRIDTestBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W51
            reason: Bucket policy not needed
          - id: W35
            reason: Logging not needed
          - id: W41
            reason: Encryption not needed
